/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uit.tkorg.pr.gui;

import java.awt.Menu;
import java.awt.event.MouseListener;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import org.apache.mahout.cf.taste.impl.common.LongPrimitiveIterator;
import uit.tkorg.pr.centralcontroller.PaperRecommender;
import uit.tkorg.pr.constant.PRConstant;
import uit.tkorg.pr.datapreparation.cbf.AuthorFVComputation;
import uit.tkorg.pr.datapreparation.cbf.PaperFVComputation;
import uit.tkorg.pr.model.Author;
import uit.tkorg.pr.model.Paper;
import uit.tkorg.utility.general.BinaryFileUtility;

/**
 *
 * @author Zoe
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    // Controller handles all request from gui:
    private PaperRecommender paperRecommender;
    private String[] response;
    private static String path=null;
    private static int check =0;// paper
    private static int chooseDataset= 0;
      public MainGUI() {
       initComponents();
       paperRecommender= new PaperRecommender();
       jTextFieldMethodCombiningAuthor.setVisible(false);
       jTextFieldMethodCombiningPaper.setVisible(false);
       jTextFieldWeightingCombiningAuthor.setVisible(false);
       jTextFieldWeightingCombiningPaper.setVisible(false);
     
       
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuItemNUSDataset1 = new javax.swing.JMenuItem();
        jMenuItemNUSDataset2 = new javax.swing.JMenuItem();
        jMenuItemMASDataset1 = new javax.swing.JMenuItem();
        buttonGroupWeightingAuthor = new javax.swing.ButtonGroup();
        buttonGroupCombiningAuthor = new javax.swing.ButtonGroup();
        buttonGroupCombiningPaper = new javax.swing.ButtonGroup();
        buttonGroupWeightingPaper = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonDataset = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonReadPaper = new javax.swing.JButton();
        jButtonReadAuthor = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButtonSave = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jTextFieldStatus = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jCheckBoxAuthorPaper = new javax.swing.JCheckBox();
        jCheckBoxAuthorPaperCit = new javax.swing.JCheckBox();
        jCheckBoxAuthorPaperRef = new javax.swing.JCheckBox();
        jCheckBoxAuthorPaperCitRef = new javax.swing.JCheckBox();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jCheckBoxPaper = new javax.swing.JCheckBox();
        jCheckBoxPaperCit = new javax.swing.JCheckBox();
        jCheckBoxPaperRef = new javax.swing.JCheckBox();
        jCheckBoxPaperCitRef = new javax.swing.JCheckBox();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jCheckBoxPaperWeightingLC = new javax.swing.JCheckBox();
        jCheckBoxPaperWeightingSIM = new javax.swing.JCheckBox();
        jCheckBoxPaperWeightingFF = new javax.swing.JCheckBox();
        jCheckBoxPaperWeightingRPY = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jCheckBoxAuthorWeightingLC = new javax.swing.JCheckBox();
        jCheckBoxAuthorWeightingSIM = new javax.swing.JCheckBox();
        jCheckBoxAuthorWeightingFF = new javax.swing.JCheckBox();
        jCheckBoxAuthorWeightingRPY = new javax.swing.JCheckBox();
        jLabelGama = new javax.swing.JLabel();
        jTextFieldGama = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMethodCombiningAuthor = new javax.swing.JTextField();
        jTextFieldMethodCombiningPaper = new javax.swing.JTextField();
        jTextFieldWeightingCombiningAuthor = new javax.swing.JTextField();
        jTextFieldWeightingCombiningPaper = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jPanel15 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel16 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextResult = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jButtonEvaluate = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButtonRecommendation = new javax.swing.JButton();
        jTextFieldTopNRecommend = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenuItemNUSDataset1.setText("NUS Dataset1");
        jMenuItemNUSDataset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNUSDataset1ActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemNUSDataset1);

        jMenuItemNUSDataset2.setText("NUS Dataset2");
        jMenuItemNUSDataset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNUSDataset2ActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemNUSDataset2);

        jMenuItemMASDataset1.setText("MAS Dataset1");
        jMenuItemMASDataset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMASDataset1ActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemMASDataset1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Import Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jToolBar1.setRollover(true);

        jButtonDataset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uit/tkorg/pr/gui/Database.png"))); // NOI18N
        jButtonDataset.setText("Dataset ");
        jButtonDataset.setFocusable(false);
        jButtonDataset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDataset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDataset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonDatasetMouseReleased(evt);
            }
        });
        jButtonDataset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDatasetActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDataset);
        jToolBar1.add(jSeparator2);

        jButtonReadPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uit/tkorg/pr/gui/Document-icon.png"))); // NOI18N
        jButtonReadPaper.setText("Papers");
        jButtonReadPaper.setFocusable(false);
        jButtonReadPaper.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReadPaper.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReadPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadPaperActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonReadPaper);

        jButtonReadAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uit/tkorg/pr/gui/User-Coat-Red-icon.png"))); // NOI18N
        jButtonReadAuthor.setText("Users");
        jButtonReadAuthor.setFocusable(false);
        jButtonReadAuthor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonReadAuthor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonReadAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReadAuthorActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonReadAuthor);
        jToolBar1.add(jSeparator3);

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uit/tkorg/pr/gui/Save-icon.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.setFocusable(false);
        jButtonSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSave);

        jButtonRefresh.setIcon(new javax.swing.ImageIcon("E:\\Luan_van\\Code\\Demo2010\\ demo10\\JavaApplication3\\Button-Refresh-icon.png")); // NOI18N
        jButtonRefresh.setText("Refesh");
        jButtonRefresh.setFocusable(false);
        jButtonRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonRefresh);

        jButtonHelp.setIcon(new javax.swing.ImageIcon("E:\\Luan_van\\Code\\Demo2010\\ demo10\\JavaApplication3\\Button-Help-icon.png")); // NOI18N
        jButtonHelp.setText("Help");
        jButtonHelp.setFocusable(false);
        jButtonHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHelp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonHelp);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(filler1);

        jTextFieldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStatusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jTextFieldStatus))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextFieldStatus.getAccessibleContext().setAccessibleName("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Method Recommendation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Preparation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11))); // NOI18N

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Method Combining AuthorFV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        buttonGroupCombiningAuthor.add(jCheckBoxAuthorPaper);
        jCheckBoxAuthorPaper.setText("Feature Vector of Paper");
        jCheckBoxAuthorPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAuthorPaperActionPerformed(evt);
            }
        });

        buttonGroupCombiningAuthor.add(jCheckBoxAuthorPaperCit);
        jCheckBoxAuthorPaperCit.setText("Feature Vector of Paper and Citation");
        jCheckBoxAuthorPaperCit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAuthorPaperCitActionPerformed(evt);
            }
        });

        buttonGroupCombiningAuthor.add(jCheckBoxAuthorPaperRef);
        jCheckBoxAuthorPaperRef.setText("Feature Vector of Paper and Reference");
        jCheckBoxAuthorPaperRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAuthorPaperRefActionPerformed(evt);
            }
        });

        buttonGroupCombiningAuthor.add(jCheckBoxAuthorPaperCitRef);
        jCheckBoxAuthorPaperCitRef.setText("Feature Vector of Paper, Citation and Reference");
        jCheckBoxAuthorPaperCitRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAuthorPaperCitRefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBoxAuthorPaperCit)
            .addComponent(jCheckBoxAuthorPaperRef)
            .addComponent(jCheckBoxAuthorPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jCheckBoxAuthorPaperCitRef)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxAuthorPaper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAuthorPaperCit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAuthorPaperRef, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAuthorPaperCitRef)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Method Combining PaperFV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        buttonGroupCombiningPaper.add(jCheckBoxPaper);
        jCheckBoxPaper.setText("Feature Vector of Paper");
        jCheckBoxPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPaperActionPerformed(evt);
            }
        });

        buttonGroupCombiningPaper.add(jCheckBoxPaperCit);
        jCheckBoxPaperCit.setText("Feature Vector of Paper and Citation");
        jCheckBoxPaperCit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPaperCitActionPerformed(evt);
            }
        });

        buttonGroupCombiningPaper.add(jCheckBoxPaperRef);
        jCheckBoxPaperRef.setText("Feature Vector of Paper and Reference");
        jCheckBoxPaperRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPaperRefActionPerformed(evt);
            }
        });

        buttonGroupCombiningPaper.add(jCheckBoxPaperCitRef);
        jCheckBoxPaperCitRef.setText("Feature Vector of Paper, Citation and Reference");
        jCheckBoxPaperCitRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPaperCitRefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBoxPaperCit)
            .addComponent(jCheckBoxPaperRef)
            .addComponent(jCheckBoxPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jCheckBoxPaperCitRef)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxPaper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPaperCit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPaperRef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPaperCitRef)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Weighting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroupWeightingPaper.add(jCheckBoxPaperWeightingLC);
        jCheckBoxPaperWeightingLC.setText("LC");
        jCheckBoxPaperWeightingLC.setEnabled(false);
        jCheckBoxPaperWeightingLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPaperWeightingLCActionPerformed(evt);
            }
        });

        buttonGroupWeightingPaper.add(jCheckBoxPaperWeightingSIM);
        jCheckBoxPaperWeightingSIM.setText("SIM");
        jCheckBoxPaperWeightingSIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPaperWeightingSIMActionPerformed(evt);
            }
        });

        buttonGroupWeightingPaper.add(jCheckBoxPaperWeightingFF);
        jCheckBoxPaperWeightingFF.setText("FF");
        jCheckBoxPaperWeightingFF.setEnabled(false);
        jCheckBoxPaperWeightingFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPaperWeightingFFActionPerformed(evt);
            }
        });

        buttonGroupWeightingPaper.add(jCheckBoxPaperWeightingRPY);
        jCheckBoxPaperWeightingRPY.setText("RPY");
        jCheckBoxPaperWeightingRPY.setEnabled(false);
        jCheckBoxPaperWeightingRPY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPaperWeightingRPYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxPaperWeightingLC)
                    .addComponent(jCheckBoxPaperWeightingSIM)
                    .addComponent(jCheckBoxPaperWeightingFF)
                    .addComponent(jCheckBoxPaperWeightingRPY))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jCheckBoxPaperWeightingLC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPaperWeightingSIM, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPaperWeightingRPY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxPaperWeightingFF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Weighting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroupWeightingAuthor.add(jCheckBoxAuthorWeightingLC);
        jCheckBoxAuthorWeightingLC.setText("LC");
        jCheckBoxAuthorWeightingLC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxAuthorWeightingLCMouseClicked(evt);
            }
        });

        buttonGroupWeightingAuthor.add(jCheckBoxAuthorWeightingSIM);
        jCheckBoxAuthorWeightingSIM.setText("SIM");
        jCheckBoxAuthorWeightingSIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAuthorWeightingSIMActionPerformed(evt);
            }
        });

        buttonGroupWeightingAuthor.add(jCheckBoxAuthorWeightingFF);
        jCheckBoxAuthorWeightingFF.setText("FF");
        jCheckBoxAuthorWeightingFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAuthorWeightingFFActionPerformed(evt);
            }
        });

        buttonGroupWeightingAuthor.add(jCheckBoxAuthorWeightingRPY);
        jCheckBoxAuthorWeightingRPY.setText("RPY");
        jCheckBoxAuthorWeightingRPY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAuthorWeightingRPYActionPerformed(evt);
            }
        });

        jLabelGama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGama.setText("Gamma:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxAuthorWeightingSIM)
                            .addComponent(jCheckBoxAuthorWeightingRPY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGama))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxAuthorWeightingFF)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jCheckBoxAuthorWeightingLC)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelGama)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAuthorWeightingLC)
                    .addComponent(jLabelGama))
                .addGap(2, 2, 2)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAuthorWeightingSIM)
                    .addComponent(jTextFieldGama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAuthorWeightingRPY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jCheckBoxAuthorWeightingFF)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        filler3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("BUILD PROFILE PAPER");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("BUILD PROFILE USER");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMethodCombiningAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldWeightingCombiningAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTextFieldMethodCombiningPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldWeightingCombiningPaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMethodCombiningAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMethodCombiningPaper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldWeightingCombiningAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldWeightingCombiningPaper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filler3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Content based", jPanel4);

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recommendation algorithm ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox9.setText("Pearson Correlation");

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox10.setText("Cosine similarity");

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox15.setText("SVD algorithm");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox15))
                .addGap(0, 416, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox15)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Preparation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setText("Build Matrix Input");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addGap(0, 128, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose Neighbor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Collaborative filtering", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hybrid", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Result", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jTextResult.setColumns(20);
        jTextResult.setRows(5);
        jScrollPane1.setViewportView(jTextResult);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Evaluation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jButtonEvaluate.setText("EVALUATION");
        jButtonEvaluate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEvaluateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEvaluate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonEvaluate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recommendation ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jButtonRecommendation.setText("RECOMMENDATION");
        jButtonRecommendation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecommendationActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Top_N Recommend");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRecommendation, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jTextFieldTopNRecommend)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTopNRecommend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRecommendation, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jMenu1.setText("File");

        jMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOpen);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Save");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Exit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenu3.setText("Load Dataset");

        jMenuItem1.setText("NUS Dataset1");
        jMenu3.add(jMenuItem1);

        jMenuItem11.setText("MAS Dataset1");
        jMenu3.add(jMenuItem11);

        jMenu2.add(jMenu3);

        jMenuItem5.setText("ReadAllListPaper");
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("ReadAllList Author");
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("AuthorFVComputation");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("PaperFVComputation");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("BuildMatrixInputCF");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Recommendation");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Evaluation");
        jMenu2.add(jMenuItem10);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReadPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadPaperActionPerformed
        // TODO add your handling code here:
        jTextFieldStatus.setText("Reading papers... ");
        if(chooseDataset==0)
        response = paperRecommender.guiRequestHandler("Read paper from NUS_DATASET1",path);
        else if(chooseDataset == 1)
        response = paperRecommender.guiRequestHandler("Read paper from NUS_DATASET2",path);  
             else 
            response = paperRecommender.guiRequestHandler("Read paper from MAS_DATASET1", path);
            jTextFieldStatus.setText(jTextFieldStatus.getText() + response[0]);
        check =0;
    }//GEN-LAST:event_jButtonReadPaperActionPerformed

    private void jButtonReadAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReadAuthorActionPerformed
        // TODO add your handling code here:
        jTextFieldStatus.setText("Reading authors... ");
        if(chooseDataset==0)
        response = paperRecommender.guiRequestHandler("Read author from NUS_DATASET1",path);
        else if(chooseDataset == 1)
             response = paperRecommender.guiRequestHandler("Read author from NUS_DATASET2",path);
        else 
             response = paperRecommender.guiRequestHandler("Read paper from MAS_DATASET1", path);
        jTextFieldStatus.setText(jTextFieldStatus.getText() + response[0]);
        check=1;
    }//GEN-LAST:event_jButtonReadAuthorActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fc.showSaveDialog(this);
        if (check==0){
            response = paperRecommender.guiRequestHandler("Save paper",fc.getSelectedFile().getAbsolutePath());
        }else if(check==1){
            response = paperRecommender.guiRequestHandler("Save author",fc.getSelectedFile().getAbsolutePath());
                 }else{
                 paperRecommender.resultEvaluation= jTextResult.getText();
                 response = paperRecommender.guiRequestHandler("Save result evaluation",fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonRecommendationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecommendationActionPerformed
        // TODO add your handling code here:
        jTextFieldStatus.setText("Recommendation... ");
        paperRecommender.topN= Integer.parseInt(jTextFieldTopNRecommend.getText().toString());
        response = paperRecommender.guiRequestHandler("Recommend", null);
      //  jTextResult.setText(response[1]);
        jTextFieldStatus.setText(jTextFieldStatus.getText() + response[0]);
    }//GEN-LAST:event_jButtonRecommendationActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButtonEvaluateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEvaluateActionPerformed
        // TODO add your handling code here:
        check=3;
        jTextFieldStatus.setText("Evaluating... ");
        jTextResult.append(jTextFieldMethodCombiningAuthor.getText()+" "+jTextFieldWeightingCombiningAuthor.getText()+" "+
        jTextFieldMethodCombiningPaper.getText()+" "+jTextFieldWeightingCombiningPaper.getText()+"\r\n");
        response = paperRecommender.guiRequestHandler("Precision", null);
        jTextResult.append(response[1]);
        response = paperRecommender.guiRequestHandler("Recall", null);
        jTextResult.append(response[1]);
        response = paperRecommender.guiRequestHandler("F1", null);
        jTextResult.append(response[1]);
        response = paperRecommender.guiRequestHandler("MAP", null);
        jTextResult.append(response[1]);
        response = paperRecommender.guiRequestHandler("NDCG", null);
        jTextResult.append(response[1]);
        response = paperRecommender.guiRequestHandler("MRR", null);
        jTextResult.append(response[1]+"\n");
        jTextFieldStatus.setText(jTextFieldStatus.getText() + response[0]);
    }//GEN-LAST:event_jButtonEvaluateActionPerformed

    private void jTextFieldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStatusActionPerformed
    
    private void jButtonDatasetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDatasetActionPerformed
        // TODO add your handling code here
          
    }//GEN-LAST:event_jButtonDatasetActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fc.showOpenDialog(this);
        path= fc.getSelectedFile().getAbsolutePath();
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
       buttonGroupWeightingAuthor.clearSelection();
       buttonGroupCombiningAuthor.clearSelection();
       buttonGroupWeightingPaper.clearSelection();
       buttonGroupCombiningPaper.clearSelection();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jCheckBoxAuthorWeightingRPYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAuthorWeightingRPYActionPerformed
        // TODO add your handling code here:
        jTextFieldStatus.setText("Computing author feature vector with RPY weight... ");
        paperRecommender.weighting = 2;
        response = paperRecommender.guiRequestHandler("Build profile user", null);
        jTextFieldWeightingCombiningAuthor.setText("with RPY weighting\n");
        jTextFieldStatus.setText(jTextFieldStatus.getText() + response[0]);
    }//GEN-LAST:event_jCheckBoxAuthorWeightingRPYActionPerformed

    private void jCheckBoxAuthorWeightingFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAuthorWeightingFFActionPerformed
        // TODO add your handling code here:
        jTextFieldStatus.setText("Computing author feature vector with Forgetting Factor weight... ");
        paperRecommender.weighting = 3;
        paperRecommender.gama= Double.parseDouble(jTextFieldGama.getText());
        response = paperRecommender.guiRequestHandler("Build profile user", null);
        jTextFieldWeightingCombiningAuthor.setText("withFF weighting\n");
        jTextFieldStatus.setText(jTextFieldStatus.getText() + response[0]);
    }//GEN-LAST:event_jCheckBoxAuthorWeightingFFActionPerformed

    private void jCheckBoxAuthorWeightingSIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAuthorWeightingSIMActionPerformed
        // TODO add your handling code here:
        jTextFieldStatus.setText("Computing author feature vector with cosine weight... ");
        paperRecommender.weighting = 1;
        response = paperRecommender.guiRequestHandler("Build profile user", null);
        jTextFieldWeightingCombiningAuthor.setText("with SIM weighting\n");
        jTextFieldStatus.setText(jTextFieldStatus.getText() + response[0]);
    }//GEN-LAST:event_jCheckBoxAuthorWeightingSIMActionPerformed

    private void jCheckBoxPaperWeightingRPYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPaperWeightingRPYActionPerformed
        // TODO add your handling code here:
         jTextFieldWeightingCombiningPaper.setText("with RPY weighting\n");
    }//GEN-LAST:event_jCheckBoxPaperWeightingRPYActionPerformed

    private void jCheckBoxPaperWeightingFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPaperWeightingFFActionPerformed
        // TODO add your handling code here:
         jTextFieldWeightingCombiningPaper.setText("with FF weighting\n");
    }//GEN-LAST:event_jCheckBoxPaperWeightingFFActionPerformed

    private void jCheckBoxPaperWeightingSIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPaperWeightingSIMActionPerformed
        // TODO add your handling code here:
        jTextFieldStatus.setText("Computing paper feature vector with SIM weight... ");
        //   paperRecommender.weighting = 2;
        response = paperRecommender.guiRequestHandler("Build profile paper", null);
        jTextFieldWeightingCombiningPaper.setText("with SIM weighting\n");
        jTextFieldStatus.setText(jTextFieldStatus.getText() + response[0]);

    }//GEN-LAST:event_jCheckBoxPaperWeightingSIMActionPerformed

    private void jCheckBoxPaperWeightingLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPaperWeightingLCActionPerformed
        // TODO add your handling code here:
         jTextFieldWeightingCombiningPaper.setText("with LC weighting\n");
    }//GEN-LAST:event_jCheckBoxPaperWeightingLCActionPerformed

    private void jCheckBoxPaperCitRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPaperCitRefActionPerformed
        // TODO add your handling code here:
        paperRecommender.combiningPaper=3;
        jTextFieldMethodCombiningPaper.setText("Combining profile paper by Paper+Cit+Ref");
    }//GEN-LAST:event_jCheckBoxPaperCitRefActionPerformed

    private void jCheckBoxPaperRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPaperRefActionPerformed
        // TODO add your handling code here:
        paperRecommender.combiningPaper=2;
        jTextFieldMethodCombiningPaper.setText("Combining profile paper by Paper+Ref");
    }//GEN-LAST:event_jCheckBoxPaperRefActionPerformed

    private void jCheckBoxPaperCitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPaperCitActionPerformed
        // TODO add your handling code here:
        paperRecommender.combiningPaper=1;
        jTextFieldMethodCombiningPaper.setText("Combining profile paper by Paper+Cit");
    }//GEN-LAST:event_jCheckBoxPaperCitActionPerformed

    private void jCheckBoxPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPaperActionPerformed
        // TODO add your handling code here:
        paperRecommender.combiningPaper=0;
        jTextFieldMethodCombiningPaper.setText("Combining profile paper by Paper");
    }//GEN-LAST:event_jCheckBoxPaperActionPerformed

    private void jCheckBoxAuthorPaperCitRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAuthorPaperCitRefActionPerformed
        // TODO add your handling code here:
        paperRecommender.combiningAuthor=3;
        jTextFieldMethodCombiningAuthor.setText("Combining profile author by Paper+Cit+Ref");
    }//GEN-LAST:event_jCheckBoxAuthorPaperCitRefActionPerformed

    private void jCheckBoxAuthorPaperRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAuthorPaperRefActionPerformed
        // TODO add your handling code here:
        paperRecommender.combiningAuthor=2;
        jTextFieldMethodCombiningAuthor.setText("Combining profile author by Paper+Ref");
 
    }//GEN-LAST:event_jCheckBoxAuthorPaperRefActionPerformed

    private void jCheckBoxAuthorPaperCitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAuthorPaperCitActionPerformed
        // TODO add your handling code here:
        paperRecommender.combiningAuthor=1;
        jTextFieldMethodCombiningAuthor.setText("Combining profile author by Paper+ Cit");
    }//GEN-LAST:event_jCheckBoxAuthorPaperCitActionPerformed

    private void jCheckBoxAuthorPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAuthorPaperActionPerformed
        // TODO add your handling code here:
       if(jCheckBoxAuthorPaper.isSelected())
        paperRecommender.combiningAuthor=0;
        jTextFieldMethodCombiningAuthor.setText("Combining profile author by Paper");
             
    }//GEN-LAST:event_jCheckBoxAuthorPaperActionPerformed

    private void jButtonDatasetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDatasetMouseReleased
        // TODO add your handling code here:
        jPopupMenu.show(this,evt.getX(),evt.getY()+1);
    }//GEN-LAST:event_jButtonDatasetMouseReleased

    private void jMenuItemNUSDataset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNUSDataset1ActionPerformed
        // TODO add your handling code here:
        path = PRConstant.FOLDER_NUS_DATASET1;
        chooseDataset = 0;
        jTextFieldStatus.setText(path);
    }//GEN-LAST:event_jMenuItemNUSDataset1ActionPerformed

    private void jMenuItemMASDataset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMASDataset1ActionPerformed
        // TODO add your handling code here:
        path = PRConstant.FOLDER_MAS_DATASET1;
        chooseDataset = 2;
    }//GEN-LAST:event_jMenuItemMASDataset1ActionPerformed

    private void jCheckBoxAuthorWeightingLCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxAuthorWeightingLCMouseClicked
        // TODO add your handling code here:
//        if(jCheckBoxAuthorWeightingLC.isSelected())
//            jCheckBoxAuthorWeightingLC.setSelected(false);
    }//GEN-LAST:event_jCheckBoxAuthorWeightingLCMouseClicked

    private void jMenuItemNUSDataset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNUSDataset2ActionPerformed
        // TODO add your handling code here:
        path = PRConstant.FOLDER_NUS_DATASET2;
        chooseDataset = 1;
        jTextFieldStatus.setText(path); 
    }//GEN-LAST:event_jMenuItemNUSDataset2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCombiningAuthor;
    private javax.swing.ButtonGroup buttonGroupCombiningPaper;
    private javax.swing.ButtonGroup buttonGroupWeightingAuthor;
    private javax.swing.ButtonGroup buttonGroupWeightingPaper;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonDataset;
    private javax.swing.JButton jButtonEvaluate;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonReadAuthor;
    private javax.swing.JButton jButtonReadPaper;
    private javax.swing.JButton jButtonRecommendation;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JCheckBox jCheckBoxAuthorPaper;
    private javax.swing.JCheckBox jCheckBoxAuthorPaperCit;
    private javax.swing.JCheckBox jCheckBoxAuthorPaperCitRef;
    private javax.swing.JCheckBox jCheckBoxAuthorPaperRef;
    private javax.swing.JCheckBox jCheckBoxAuthorWeightingFF;
    private javax.swing.JCheckBox jCheckBoxAuthorWeightingLC;
    private javax.swing.JCheckBox jCheckBoxAuthorWeightingRPY;
    private javax.swing.JCheckBox jCheckBoxAuthorWeightingSIM;
    private javax.swing.JCheckBox jCheckBoxPaper;
    private javax.swing.JCheckBox jCheckBoxPaperCit;
    private javax.swing.JCheckBox jCheckBoxPaperCitRef;
    private javax.swing.JCheckBox jCheckBoxPaperRef;
    private javax.swing.JCheckBox jCheckBoxPaperWeightingFF;
    private javax.swing.JCheckBox jCheckBoxPaperWeightingLC;
    private javax.swing.JCheckBox jCheckBoxPaperWeightingRPY;
    private javax.swing.JCheckBox jCheckBoxPaperWeightingSIM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelGama;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemMASDataset1;
    private javax.swing.JMenuItem jMenuItemNUSDataset1;
    private javax.swing.JMenuItem jMenuItemNUSDataset2;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldGama;
    private javax.swing.JTextField jTextFieldMethodCombiningAuthor;
    private javax.swing.JTextField jTextFieldMethodCombiningPaper;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldTopNRecommend;
    private javax.swing.JTextField jTextFieldWeightingCombiningAuthor;
    private javax.swing.JTextField jTextFieldWeightingCombiningPaper;
    private javax.swing.JTextArea jTextResult;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
